apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: harvester  # Stores the DB on your Harvester cluster disk
  resources:
    requests:
      storage: 10Gi