#apiVersion: v1
#kind: Secret
#metadata:
#  name: cloudflare-api-token
#  namespace: cert-manager
#type: Opaque
#stringData:
#  api-token: "<CF_API_TOKEN>"

#Run this: kubectl -n cert-manager create secret generic cloudflare-api-token \
#  --from-literal=api-token='<CF_API_TOKEN>'
