apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      nodeSelector:
        nvidia.com/gpu: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      priorityClassName: "system-node-critical"
      hostNetwork: true
      hostPID: true
      containers:
        - image: nvcr.io/nvidia/k8s-device-plugin:v0.18.0
          name: nvidia-device-plugin-ctr
          env:
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          args:
            - "--fail-on-init-error=false"
            - "--device-discovery-strategy=nvml"
            - "--device-list-strategy=envvar"
            - "--pass-device-specs=true"
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: host-root
              mountPath: /host
              readOnly: true
              mountPropagation: HostToContainer
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: host-root
          hostPath:
            path: /