---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCQn1Zf/qUh8CgGRDFdRSJsDauyPTTMBzein0yKCVy1g0OmV7sNjTSfsEML1JR3ZyNvLkhdXiepFec5aG/iVfNBs9Mp+CReawLUBzb/Hk9KDwMRIGlZTYTFeeZvDoQ6RFVm4oUkRu9V7p87vqOJhr53tY86a95A7ET0dTl0D++hcYc39aVFenY4kAr+YFxTxcqCxpnoLOcvdjMyN3kZm3taP7YPs15mMV+ne/nST7y6kAFfWImYMc8WeXn7BJEa0/+9J4CqBCiWYp0V8pSXmqAmeDWpwKGrWXsN0X54UYS431U73ELrvvQb+6FgWjqwKG9K7wdGFOftkcpNkB9sThnHIsz2PEJngafg5JB6rPJEtWg+m9w4B1S1qUsWFadBhCllRATt6RoTVLpA80eWrzLE/wFyBtL3hDFB8JuHI9EwGTl30efGlv7FpgDIg0rN/KwgY6Sl2lyWL5d9u863AiH69m1naD4L/7v+Y2iTqn9LH85RCILvudtkTmHfRW169EhFt0xGAwiYbTGbkSv/630QHFSFAGW5PHKHO4aa9cOq31VW3GVaFsEDwq27g63gHB23nvHOZP9UawGJcCNG+Os+C/x5wGVxf1N+3Fn5NEQ3+efnwDFpwTG6+5Jgay5BmYNjrImclPH+vo6PmAYqf0qv13gl2/eO6c/5bHIwKlAXerv3OlG3/yLwKuNb5IoBEzOCOe4slJbbWDGlReCfph7WjntgF3DuyBb8z4h1QN4CgI2ERoat/znA
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
