---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2r
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: ollama
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: webui-data
              mountPath: /app/backend/data
          env:
            - name: OLLAMA_BASE_URL
              value: "http://10.10.10.44:11434"
            - name: OPENAI_API_BASE_URL
              value: "http://10.10.10.44:11434/v1"
            - name: ENABLE_OLLAMA_API
              value: "false"
            - name: WEBUI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ollama-secrets
                  key: webui-secret-key
            - name: ENABLE_RAG_WEB_SEARCH
              value: "true"
            - name: RAG_WEB_SEARCH_ENGINE
              value: "searxng"
            - name: SEARXNG_QUERY_URL
              value: "http://searxng:8080/search?q=<query>"
            - name: RAG_WEB_SEARCH_RESULT_COUNT
              value: "5"
            - name: RAG_WEB_SEARCH_CONCURRENT_REQUESTS
              value: "10"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: webui-data
          persistentVolumeClaim:
            claimName: open-webui-data
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: ollama
spec:
  selector:
    app: open-webui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
