---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: ollama
data:
  settings.yml: |
    use_default_settings: true
    server:
      secret_key: "REPLACEME"
      limiter: false
      image_proxy: true
    ui:
      static_use_hash: true
    search:
      safe_search: 0
      autocomplete: "google"
      formats:
        - html
        - json
    engines:
      - name: google
        disabled: false
      - name: duckduckgo
        disabled: false
      - name: bing
        disabled: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: ollama
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      initContainers:
        - name: config-init
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              echo "Starting config initialization..."
              if [ -z "$SEARXNG_SECRET" ]; then
                echo "ERROR: SEARXNG_SECRET environment variable is not set"
                exit 1
              fi
              echo "Secret key found, generating config..."
              # Use | as delimiter instead of / to avoid issues with base64 strings
              sed "s|REPLACEME|${SEARXNG_SECRET}|g" /config-template/settings.yml > /config/settings.yml
              echo "Config generated successfully"
          env:
            - name: SEARXNG_SECRET
              valueFrom:
                secretKeyRef:
                  name: ollama-secrets
                  key: searxng-secret-key
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: config
              mountPath: /config
      containers:
        - name: searxng
          image: searxng/searxng:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/searxng
          env:
            - name: SEARXNG_BASE_URL
              value: "http://searxng:8080/"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config-template
          configMap:
            name: searxng-config
        - name: config
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: searxng
  namespace: ollama
  labels:
    app: searxng
spec:
  selector:
    app: searxng
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP