---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-bouncer-config
  namespace: crowdsec
data:
  crowdsec-cloudflare-bouncer.yaml: |
    crowdsec_lapi_url: http://crowdsec-service.crowdsec.svc.cluster.local:8080
    crowdsec_lapi_key: "${BOUNCER_API_KEY}"
    crowdsec_update_frequency: 10s
    include_scenarios_containing: []
    exclude_scenarios_containing: []
    only_include_decisions_from: []
    
    cloudflare_config:
      accounts:
        - id: "${CLOUDFLARE_ACCOUNT_ID}"
          token: "${CLOUDFLARE_TOKEN}"
          ip_list_prefix: crowdsec
          default_action: challenge  # 'challenge' (Captcha) or 'block'
          zones:
            - zone_id: "${CLOUDFLARE_ZONE_ID}"
              actions:
                - challenge # Actions to apply (challenge/block)
      update_frequency: 30s

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-bouncer
  namespace: crowdsec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-bouncer
  template:
    metadata:
      labels:
        app: cloudflare-bouncer
    spec:
      containers:
        - name: cloudflare-bouncer
          image: crowdsecurity/cloudflare-bouncer:latest
          # We use envsubst to inject secrets into the config at runtime
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add gettext && \
              envsubst < /config/crowdsec-cloudflare-bouncer.yaml > /etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml && \
              /usr/local/bin/crowdsec-cloudflare-bouncer
          envFrom:
            - secretRef:
                name: cloudflare-bouncer-secrets
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: cloudflare-bouncer-config