---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAYSMjhLIrrPA+UIu3VFNxjG0S9k40wh+mHld4kspnqxieQHMuoStEWCuW1Z210jOvi64QP/UIxAmm1V/Z1Ch1AIAAJcRRWceTvPKLiG3unwjIyxbULPSOhcpXKLHbK8F4BjiYL55STzOA8yo/SrH/zQVe7LLMavRixqGDgjYSx9k1XU3BCrvFDpLpDF9bhu2zevAVy+DfSheVk+q20NcS2aRm3rj7naWXWzRc5vHqRDxr12/+HoalvPsz2GD8YCmQuUnyfL22DU5qRbNj9mgZZzbbIKvSPQsUPO8ulYuNo30cMiwMzCZx4GlfbJVEdSmVYVh0rsCHjPADj/EacmAs9d3dDhEff9swdtCYup1abwZ1A5Ngc39ot7vB9R7KmBkrQv4alXjYnZcupROhfNOmzj7Jgx/B5R+5NOpOLlG5RngSzJ0oHyACzVV/VDDhLVNCupeL0Y3o+4iSX9nMS89jAMqIPvHng1DRJjm4T6cFJjz5JHN7afNAOqG4OJt33IKwQii7xr4y1nzKZrd56EgA4vFhjTXJ+vkPfu49Ayu/CMLFTqczYlOX0Pq5aOo9sAA7SYRH1Zeb7XdCYKw7VYc8QQdmtKfNmi8Kx2ZQ8fOJjlIVCNyQDIbm6btZcWBXkKCbLRPu4blO7EMl/RTkZuxiWcdAWusb2DQDYe23NwXC6V2M8gPay7dNi5lIiH/yn5fZsLSuKnlSUWhHTEFra7L4CjuIwcB5MpifJ6qUbP+eUAWruhUYyNcELhcz7kU+jagtpIPg/OAn9EEasa7NTNcRd6Qz5aisgJFDvmoDMsy0fRpr8preYAVT+2mLfuyolFaqyxqgeScZyD9CTX60sY8XCldo+GrQaU4bIcCVnt6v9d5Ebf25MyPQNw1LKNFKoC0axMA==
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
