---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgB6oqrDLTj1H9R1NutXllO+pZ0uQ0HhNxNDIM/FzMSlnZuorDYAEdH7YV6OxjLB23ZP510yMLi/zXO8kAjNIMvMgkZlb8eYNZbKX2D//PxtrBw/yPlAyUVIjpv0Ntx8uH8LJubfEzCn+PTDbUyk7lr41YshQNiA6UhtzPRxA/knLhIcp30nOfSG870hMJ3nlXlM8vAbHIzoSIzCp99pCtDSeQXOs5thUF6appTFv6qRHQMzJ3tdB0AoAbSP0WPs9f2YqoezRwZF1Foz8mw2O3z1SfFOkewtHC3UoZSJmzgfcDnSsgtq6oacnDboNZdae0RFlfXC++7xChSex0Q+H8YmuLTwVZanZo3MY5m+RzQ+/+izjr4ezevuVjV4cb8exvkVxpWi/DjZWLmVRDSw385OqJ6gvqLrBAGvWz41zp5B9IzxvI1uViHXSOqLg1wmYftN8LT6VZkHMzksC30XWjTKhCnD5MXGGvwkAURISPrYUcMpYhfE07YWVFZ0W3eiYB7RlJ/QoA8gR6GPFVKJXp5/Om8psGGNZ37lb6PkN7LI5ENCtX2rH/2BHUd83PxE5KIe8FzIQ/PLgzpqJrpuIvt4RyubQcFoCMcJk5s/tA9vER4otlsMNVUY3l7TW3cwYCk/epPrk1MSFUhPrV+RHXFvzzGhIwWcIisDq2ySmcV4+Slxk9zcW5zTNLH9uKZvZ0Lp7tt9vqwYSfZFHPy4fTFCjMsH0CpPiBgs96Z2vQcnRcVuJMoAbdlumJIW1wJX06dUPJmfB7GoUwOu1W40zKaQsZU3EUrmU5DvpLBaDaIYTd0Jble9U7F6iiwHLFak8ea2Iv220oOXrgfR
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
    type: Opaque
