---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgB4OjJmIPwpt8V2R1A4sB12r2t2XPgmDQU13qeH75PX7zyLOefVQn4xPVyxEothLsH5ABp8TAEbtt3nXQfFURDKUb5dw8tCcQNbEtdmwnsL6iWklrYlRH0iZciTPAEyhsrvZZoJOtULTsc6MtGFEGO0t+OuOf+NDiqRftTm78DdVigRayyWyMN6Y+I8OMA2Lf1RAjKH24auZcN8ITgkuHlKC8ubmc2voidNjAQmk6vNi6Jm9yHmAAoRMWiAZn2QhK3yUXEutIeibt0cjkQEqIOdAimsrhM8CbuWq2SWvW8CRSRmuhpBdPnmdUec+7hnahhKfL/jlnFCfDh2fKSDPuHjmqutvg6nPD222m6QOTXOONuHa7gc2HPRhhmblUvV2HYGYDESK61pz7yN4TPco0+1PnOMB9BNnHV/RQoMVpbv4jWL6PsZatZh6Duf7z++VtJpTMkTGUvmtN83sBD4CHcpI2nHBPlcu3lFfTLlA/zBLBB+MAoW5A+s3mKu6cafgx35zEAZDdlvPO7L/n7YYyXzHbJO+rXmrhSy9LYlQ6eEpfN+XIhHZHoqREgWW/F5otXSSvnPx9/J4MD9YXVgrTrQhOaCANX3LA9V1FisB5Wh98RNZRYGoikO+BjFLgMZ9WqU07zBrXk6TfPxj2743YJkvMLTmbRm8I7UGEuCGtaOX06sjed63+HJLUTBMRE1ZQtybaZAWbE5teHgPQQEoPCLJpT0BYAG3nufe10ZXOkyqy3saaH3P6J8M1wp6iqyw3ujbHSaWCyXtFd0LHBS3G1CHLk/MqJ+c2uNVYG22s6N6jBQmAyiwaJZdVoFdPb0qMoyEKTHjtnXOwV2NUyTjNseZgTc38Hg4d7VgPNY6BUADKqe3Q==
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
