---
# VolumeSnapshotClass for Longhorn CSI Snapshots
# This enables Velero to create CSI snapshots of Longhorn volumes
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: longhorn-snapshot-vsc
  namespace: velero
  labels:
    # This label tells Velero to use this VolumeSnapshotClass
    # for Longhorn-provisioned PVCs during backup
    velero.io/csi-volumesnapshot-class: "true"
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  # 'snap' creates in-cluster snapshots (fast, local)
  # 'bak' creates Longhorn backups (slow, requires Longhorn BackupTarget)
  # We use 'snap' because Velero's data mover handles uploading to S3
  type: snap