# --- Config Storage ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-2r
  resources: { requests: { storage: 10Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  labels: { app: bazarr }
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels: { app: bazarr }
  template:
    metadata:
      labels: { app: bazarr }
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: stack
                    operator: In
                    values: [ "media-anchor" ]
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          env:
            - { name: PUID, value: "1000" }
            - { name: PGID, value: "1000" }
            - { name: TZ, value: "America/New_York" }
          ports:
            - { containerPort: 6767, name: http }
          volumeMounts:
            - { name: config, mountPath: /config }
            - { name: hot, mountPath: /media/hot }
            - { name: cold, mountPath: /media/cold }
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: config
          persistentVolumeClaim: { claimName: bazarr-config }
        - name: hot
          persistentVolumeClaim: { claimName: media-hot-pvc }
        - name: cold
          persistentVolumeClaim: { claimName: media-nfs-pvc }