apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: harvester
  resources: { requests: { storage: 5Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels: { app: jellyseerr }
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels: { app: jellyseerr }
  template:
    metadata:
      labels: { app: jellyseerr }
    spec:
      containers:
        - name: jellyseerr
          image: lscr.io/linuxserver/jellyseerr:latest
          env:
            - { name: PUID, value: "1000" }
            - { name: PGID, value: "1000" }
            - { name: TZ, value: "America/New_York" }
          ports:
            - { containerPort: 5055, name: http }
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
          volumeMounts:
            - { name: config, mountPath: /config }
      volumes:
        - name: config
          persistentVolumeClaim: { claimName: jellyseerr-config }