apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: harvester
  resources: { requests: { storage: 20Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels: { app: jellyfin }
  template:
    metadata:
      labels: { app: jellyfin }
    spec:
      # --- THE STICKY LOGIC ---
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: stack
                    operator: In
                    values: ["media-anchor"]
              topologyKey: "kubernetes.io/hostname"
      # ------------------------
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.11.3
          env:
            - { name: JELLYFIN_PublishedServerUrl, value: "https://ghostlabz.net" }
          ports:
            - { containerPort: 8096, name: http }
          resources:
            requests: { memory: "4Gi", cpu: "2000m" }
          volumeMounts:
            - { name: config, mountPath: /config }
            - { name: cache, mountPath: /cache }
            - { name: hot, mountPath: /media/hot }
            - { name: cold, mountPath: /media/cold }
      volumes:
        - name: config
          persistentVolumeClaim: { claimName: jellyfin-config }
        - name: cache
          emptyDir: {}
        - name: hot
          persistentVolumeClaim: { claimName: media-hot-pvc }
        - name: cold
          persistentVolumeClaim: { claimName: media-nfs-pvc }