apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-fast
  resources: { requests: { storage: 5Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels: { app: jellyseerr }
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels: { app: jellyseerr }
  template:
    metadata:
      labels: { app: jellyseerr }
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:2.7.3
          env:
            - { name: LOG_LEVEL, value: "info" }
            - { name: TZ, value: "America/New_York" }
          ports:
            - { containerPort: 5055, name: http }
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - { name: config, mountPath: /app/config }
      volumes:
        - name: config
          persistentVolumeClaim: { claimName: jellyseerr-config }