apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-hot-rwx-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: harvester
  resources:
    requests:
      storage: 250Gi