apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-mover
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels: { app: media-mover }
  template:
    metadata:
      labels: { app: media-mover }
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: stack
                    operator: In
                    values: [ "media-anchor" ]
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: mover
          image: alpine:latest
          command:
            - "/bin/sh"
            - "-c"
            - "apk add --no-cache bash findutils coreutils curl jq && /bin/bash /scripts/mover.sh"
          env:
            # API Keys from secret
            - name: RADARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: media-api-keys
                  key: radarr-api-key
            - name: SONARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: media-api-keys
                  key: sonarr-api-key
            # Optional: Override defaults
            - name: THRESHOLD_PERCENT
              value: "80"
            - name: TARGET_PERCENT
              value: "70"
            - name: MIN_FREE_GB
              value: "50"
            # Operational modes (for testing)
            - name: DRY_RUN
              value: "true"
            - name: MAX_FILES
              value: "5"
            # - name: DRAIN_MODE
            #   value: "false"
          volumeMounts:
            - { name: script, mountPath: /scripts }
            - { name: hot, mountPath: /media/hot }
            - { name: cold, mountPath: /media/cold }
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
      volumes:
        - name: script
          configMap: { name: media-mover-script, defaultMode: 0755 }
        - name: hot
          persistentVolumeClaim: { claimName: media-hot-pvc }
        - name: cold
          persistentVolumeClaim: { claimName: media-nfs-pvc }