apiVersion: v1
kind: ConfigMap
metadata:
  name: media-mover-script
data:
  mover.sh: |
    #!/bin/bash
    HOT="/media/hot"
    COLD="/media/cold"
    DAYS=14
    echo "Starting Mover: Moving files older than $DAYS days from $HOT to $COLD..."
    while true; do
      find "$HOT" -type f -mtime +$DAYS -not -type l | while read FILE; do
        DEST="${FILE/$HOT/$COLD}"
        mkdir -p "$(dirname "$DEST")"
        mv "$FILE" "$DEST" && ln -s "$DEST" "$FILE" && echo "Moved: $FILE"
      done
      sleep 3600
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-mover
spec:
  replicas: 1
  selector:
    matchLabels: { app: media-mover }
  template:
    metadata:
      labels: { app: media-mover }
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: stack
                    operator: In
                    values: ["media-anchor"]
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: mover
          image: alpine:latest
          command: ["/bin/sh", "/scripts/mover.sh"]
          volumeMounts:
            - { name: script, mountPath: /scripts }
            - { name: hot, mountPath: /media/hot }
            - { name: cold, mountPath: /media/cold }
      volumes:
        - name: script
          configMap: { name: media-mover-script, defaultMode: 0755 }
        - name: hot
          persistentVolumeClaim: { claimName: media-hot-pvc }
        - name: cold
          persistentVolumeClaim: { claimName: media-nfs-pvc }