apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-fast
  resources: { requests: { storage: 5Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels: { app: prowlarr }
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels: { app: prowlarr }
  template:
    metadata:
      labels: { app: prowlarr }
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          env:
            - { name: PUID, value: "1000" }
            - { name: PGID, value: "1000" }
            - { name: TZ, value: "America/New_York" }
          ports:
            - { containerPort: 9696, name: http }
          volumeMounts:
            - { name: config, mountPath: /config }
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: config
          persistentVolumeClaim: { claimName: prowlarr-config }