apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-fast
  resources: { requests: { storage: 10Gi } }
---
# --- Auto-Setup Script (Whitelist + Folders) ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbd-init-script
data:
  99-setup-stack.sh: |
    #!/bin/bash
    CONFIG="/config/sabnzbd.ini"
    # Whitelist both the public URL and the internal K8s service name
    HOSTNAMES="sabnzbd.lab.ghostlabz.net, sabnzbd, sabnzbd.media"
    
    echo "[custom-init] Starting Media Stack Bootstrap..."

    # 1. Ensure Folder Structure Exists
    if [ -d "/media/hot" ]; then
        echo "[custom-init] Creating directory structure on Hot Storage..."
        mkdir -p /media/hot/downloads/incomplete
        mkdir -p /media/hot/downloads/completed
        mkdir -p /media/hot/movies
        mkdir -p /media/hot/tv
        chmod -R 777 /media/hot/downloads
        chmod -R 777 /media/hot/movies
        chmod -R 777 /media/hot/tv
    fi

    # 2. Patch Host Whitelist
    if [ -f "$CONFIG" ]; then
      # We assume if the external domain is missing, we need to patch everything
      if ! grep -q "ghostlabz.net" "$CONFIG"; then
        echo "[custom-init] Patching Hostname Whitelist..."
        # Appends the new hostnames to the existing line
        sed -i "/^host_whitelist/ s/$/ , $HOSTNAMES/" "$CONFIG"
      fi
    fi
    echo "[custom-init] Bootstrap Complete."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  labels:
    app: sabnzbd
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels: { app: sabnzbd }
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:latest
          env:
            - { name: PUID, value: "1000" }
            - { name: PGID, value: "1000" }
            - { name: TZ, value: "America/New_York" }
          ports:
            - { containerPort: 8080, name: http }
          volumeMounts:
            - name: init-script
              mountPath: /custom-cont-init.d/99-setup-stack.sh
              subPath: 99-setup-stack.sh
            - { name: config, mountPath: /config }
            - { name: hot, mountPath: /media/hot }
            - { name: cold, mountPath: /media/cold }
          resources:
            requests:
              cpu: "2000m"
              memory: "2Gi"
      volumes:
        - name: init-script
          configMap:
            name: sabnzbd-init-script
            defaultMode: 0755
        - name: config
          persistentVolumeClaim: { claimName: sabnzbd-config }
        - name: hot
          persistentVolumeClaim: { claimName: media-hot-pvc } # Shared RWO
        - name: cold
          persistentVolumeClaim: { claimName: media-nfs-pvc } # Shared RWX