apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-v2
provisioner: driver.harvesterhci.io
parameters:
  hostStorageClass: harvester-longhorn-v2
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true