apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: harvester-cloud-provider
  namespace: kube-system
spec:
  valuesContent: |-
    # Strategy 1: Root level (Newer charts)
    extraArgs:
      - "--cloud-provider=harvester"
      - "--cloud-config=/etc/kubernetes/cloud-config"
      - "--cluster-name=homelab"
      - "--controllers=cloud-node,cloud-node-lifecycle,route"
    
    # Strategy 2: Nested (Older charts/RKE2 bundles)
    cloudControllerManager:
      extraArgs:
        - "--cloud-provider=harvester"
        - "--cloud-config=/etc/kubernetes/cloud-config"
        - "--cluster-name=homelab"
        - "--controllers=cloud-node,cloud-node-lifecycle,route"

    # CRITICAL: Keep global settings to avoid breaking the cluster ID
    global:
      cattle:
        clusterId: c-m-lvc859dv
        clusterName: homelab