apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: harvester-cloud-provider
  namespace: kube-system
spec:
  valuesContent: |-
    extraArgs:
      - "--cloud-provider=harvester"
      - "--cloud-config=/etc/kubernetes/cloud-config"
      - "--cluster-name=homelab"
      - "--controllers=cloud-node,cloud-node-lifecycle,route"

    global:
      cattle:
        clusterId: c-m-lvc859dv
        clusterName: homelab